blueprint:
  name: "Bathroom Routine v2.0.2 (Reliability Focus)"
  description: >
    **Version: 2.0.2 - Critical Fix**
    
    A completely strictly-typed rewrite focusing on reliability.
    
    **Logic Flow:**
    1. **Override:** If enabled, lights force ON (Bright White).
    2. **Turn Off:** If motion clears (and no override), lights turn OFF.
    3. **Turn On:** If motion is active, logic evaluates Time Blocks in a specific "Waterfall" order to ensure a valid state is always selected.
    
    **Time Logic (Waterfall):**
    1. **Late Night:** Checks if time is >= Night Start OR < Morning Start.
    2. **Evening:** Checks if time is >= Evening Start.
    3. **Day:** Checks if time is >= Day Start.
    4. **Morning:** Default fallback (Everything else).

  domain: automation
  input:
    # --- Devices ---
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_main:
      name: Main Lights (Ceiling & Mirrors)
      selector:
        target:
          entity:
            domain: light
    light_night:
      name: Night Light (Hue Go)
      selector:
        entity:
          domain: light

    override_entity:
      name: Override / Makeup Mode (Optional)
      description: Input Boolean. When ON, force Bright White.
      default: ""
      selector:
        entity:
          domain: input_boolean
    
    # --- Schedule (Start Times) ---
    time_morning:
      name: Morning Start
      default: "06:00:00"
      selector:
        time:
    time_day:
      name: Day Start
      default: "09:00:00"
      selector:
        time:
    time_evening:
      name: Evening Start (Toddler Wind-Down)
      default: "18:30:00"
      selector:
        time:
    time_night:
      name: Late Night Start (Sleep)
      default: "22:00:00"
      selector:
        time:

    # --- Brightness/Color Settings ---
    # Morning
    bri_morning:
      name: Morning Brightness
      default: 80
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    temp_morning:
      name: Morning Color Temp (K)
      default: 4000
      selector:
        color_temp:
          min_mireds: 153
          max_mireds: 500
          
    # Day
    bri_day:
      name: Day Brightness
      default: 100
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    temp_day:
      name: Day Color Temp (K)
      default: 3500
      selector:
        color_temp:
          min_mireds: 153
          max_mireds: 500

    # Evening
    bri_evening:
      name: Evening Brightness
      default: 50
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    temp_evening:
      name: Evening Color Temp (K)
      default: 2200
      selector:
        color_temp:
          min_mireds: 153
          max_mireds: 500

    # Late Night
    bri_night:
      name: Late Night Brightness (Hue Go)
      default: 10
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    
    enable_main_night:
      name: Enable Main Lights in Late Night?
      default: false
      selector:
        boolean:
    bri_main_night:
      name: Late Night Brightness (Main Lights)
      default: 5
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}

    # --- General ---
    motion_delay:
      name: Motion Timeout
      default: 5
      selector:
        number: {min: 1, max: 60, unit_of_measurement: "min"}
    transition_time:
      name: Transition Time
      default: 2
      selector:
        number: {min: 0, max: 10, unit_of_measurement: "s"}

mode: restart
max_exceeded: silent

trigger:
  # Motion
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: "motion_on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: 
      minutes: !input motion_delay
    id: "motion_off"
  
  # Override
  - platform: state
    entity_id: !input override_entity
    id: "override_change"

  # Time Changes (Trigger re-evaluation if lights are already on)
  - platform: time
    at: !input time_morning
    id: "time_change"
  - platform: time
    at: !input time_day
    id: "time_change"
  - platform: time
    at: !input time_evening
    id: "time_change"
  - platform: time
    at: !input time_night
    id: "time_change"

variables:
  # Inputs (Mapping for readability)
  sensor_motion: !input motion_sensor
  entity_override: !input override_entity
  enable_main_night: !input enable_main_night
  
  # Settings
  bri_morn: !input bri_morning
  bri_day: !input bri_day
  bri_even: !input bri_evening
  bri_night: !input bri_night
  bri_main_night: !input bri_main_night
  
  # Times
  t_morn: !input time_morning
  t_day: !input time_day
  t_even: !input time_evening
  t_night: !input time_night

  # States
  is_motion: "{{ is_state(sensor_motion, 'on') }}"
  is_override: >
    {% if entity_override is defined and entity_override not in [none, "", []] %}
      {{ is_state(entity_override, 'on') }}
    {% else %}
      false
    {% endif %}

action:
  - choose:
      # -----------------------------------------------------------
      # 1. OVERRIDE MODE (Highest Priority)
      # -----------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_override }}"
        sequence:
          - service: light.turn_on
            target: !input light_main
            data:
              kelvin: 5000
              brightness_pct: 100
              transition: !input transition_time
          - service: light.turn_on
            target:
              entity_id: !input light_night
            data:
              kelvin: 5000
              brightness_pct: 100
              transition: !input transition_time

      # -----------------------------------------------------------
      # 2. TURN OFF (Motion Cleared & Not Override)
      # -----------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "motion_off"
          - condition: template
            value_template: "{{ not is_override }}"
        sequence:
          - service: light.turn_off
            target: !input light_main
            data:
              transition: !input transition_time
          - service: light.turn_off
            target:
              entity_id: !input light_night
            data:
              transition: !input transition_time

      # -----------------------------------------------------------
      # 3. TURN ON (Motion Active OR Time Change)
      # -----------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ is_motion }}"
          - condition: template
            value_template: "{{ not is_override }}"
        sequence:
          - choose:
              # A. LATE NIGHT (Waterfall 1: Time >= Night OR Time < Morning)
              - conditions:
                  - condition: template
                    value_template: >
                      {{ now() >= today_at(t_night) or now() < today_at(t_morn) }}
                sequence:
                  # Hue Go -> RED
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      rgb_color: [255, 67, 0]
                      brightness_pct: !input bri_night
                      transition: !input transition_time
                  # Main Lights -> Conditional
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ enable_main_night }}"
                        sequence:
                          - service: light.turn_on
                            target: !input light_main
                            data:
                              kelvin: 2200
                              brightness_pct: !input bri_main_night
                              transition: !input transition_time
                    default:
                      - service: light.turn_off
                        target: !input light_main
                        data:
                          transition: !input transition_time

              # B. EVENING (Waterfall 2: Time >= Evening)
              - conditions:
                  - condition: template
                    value_template: "{{ now() >= today_at(t_even) }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_main
                    data:
                      kelvin: !input temp_evening
                      brightness_pct: !input bri_evening
                      transition: !input transition_time
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      kelvin: !input temp_evening
                      brightness_pct: !input bri_evening
                      transition: !input transition_time

              # C. DAY (Waterfall 3: Time >= Day)
              - conditions:
                  - condition: template
                    value_template: "{{ now() >= today_at(t_day) }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_main
                    data:
                      kelvin: !input temp_day
                      brightness_pct: !input bri_day
                      transition: !input transition_time
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      kelvin: !input temp_day
                      brightness_pct: !input bri_day
                      transition: !input transition_time

            # D. MORNING (Waterfall 4: Default/Fallback)
            default:
              - service: light.turn_on
                target: !input light_main
                data:
                  kelvin: !input temp_morning
                  brightness_pct: !input bri_morning
                  transition: !input transition_time
              - service: light.turn_on
                target:
                  entity_id: !input light_night
                data:
                  kelvin: !input temp_morning
                  brightness_pct: !input bri_morning
                  transition: !input transition_time
