blueprint:
  name: "Bathroom Routine v1.0.1 (Circadian & Toddler)"
  description: >
    **Version: 1.0.1**
    
    A smart bathroom automation utilizing Philips Hue devices.
    
    **Features:**
    *   **4-Phase Routine:** Morning, Day, Evening (Toddler Wind-Down), Late Night (Sleep).
    *   **Circadian Logic:** Automatically adjusts color temperature (Morning/Day = Cool/Neutral, Evening = Warm).
    *   **Toddler Sleep Support:** "Late Night" mode uses specific Red/Amber light (Hue Go) to preserve melatonin.
    *   **Summer Safe:** "Evening" mode enforces warm light at a fixed time (e.g. 19:00) regardless of late sunsets.
    *   **Makeup Override:** Supports an external helper (Input Boolean) to force bright cool light.
    
  domain: automation
  input:
    # --- Devices ---
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_main:
      name: Main Lights (Ceiling & Mirrors)
      description: These lights will follow the main circadian routine.
      selector:
        target:
          entity:
            domain: light
    light_night:
      name: Night Light (Hue Go)
      description: This light will turn Red during Late Night mode.
      selector:
        entity:
          domain: light

    override_entity:
      name: Override / Makeup Mode (Optional)
      description: An Input Boolean. When ON, lights turn Bright White (Makeup Mode).
      default: []
      selector:
        entity:
          domain: input_boolean
    
    # --- Schedule (Start Times) ---
    time_morning:
      name: Morning Start
      description: Cool White, High Brightness.
      default: "06:00:00"
      selector:
        time:
    time_day:
      name: Day Start
      description: Neutral White.
      default: "09:00:00"
      selector:
        time:
    time_evening:
      name: Evening Start (Toddler Wind-Down)
      description: Warm White (2200K). Set this to ~1 hour before bedtime (e.g., 18:30).
      default: "18:30:00"
      selector:
        time:
    time_night:
      name: Late Night Start (Sleep)
      description: Red Light only (Hue Go).
      default: "22:00:00"
      selector:
        time:

    # --- Brightness Settings ---
    bri_morning:
      name: Morning Brightness
      default: 80
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    bri_day:
      name: Day Brightness
      default: 100
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    bri_evening:
      name: Evening Brightness
      default: 50
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}
    bri_night:
      name: Late Night Brightness (Hue Go)
      default: 10
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}

    # --- Advanced Options ---
    enable_main_night:
      name: Enable Main Lights in Late Night?
      description: If enabled, Main Lights will turn on (very dim) during Late Night. If disabled, only the Hue Go turns on.
      default: false
      selector:
        boolean:
    bri_main_night:
      name: Late Night Brightness (Main Lights)
      description: Only used if Main Lights are enabled for Late Night.
      default: 5
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}

    motion_delay:
      name: Motion Timeout
      description: Time to wait before turning off lights.
      default: 5
      selector:
        number: {min: 1, max: 60, unit_of_measurement: "min"}
    transition_time:
      name: Transition Time
      default: 2
      selector:
        number: {min: 0, max: 10, unit_of_measurement: "s"}

mode: restart
max_exceeded: silent

trigger:
  # Motion
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: "motion_on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: 
      minutes: !input motion_delay
    id: "motion_off"
  
  # Override Toggle
  - platform: state
    entity_id: !input override_entity
    id: "override_change"

  # Time Blocks (Update light state if already on)
  - platform: time
    at: !input time_morning
    id: "schedule_change"
  - platform: time
    at: !input time_day
    id: "schedule_change"
  - platform: time
    at: !input time_evening
    id: "schedule_change"
  - platform: time
    at: !input time_night
    id: "schedule_change"

variables:
  # Inputs
  sensor_motion: !input motion_sensor
  entity_override: !input override_entity
  enable_main_night: !input enable_main_night
  bri_main_night: !input bri_main_night
  
  t_morning: !input time_morning
  t_day: !input time_day
  t_evening: !input time_evening
  t_night: !input time_night

  # Current State
  is_motion: "{{ is_state(sensor_motion, 'on') }}"
  
  # Robust Override Check
  is_override: >
    {% if entity_override %}
      {{ is_state(entity_override, 'on') }}
    {% else %}
      false
    {% endif %}

  # Determine Logic Phase
  current_phase: >
    {% set t = now().strftime('%H:%M:%S') %}
    {% if t >= t_night or t < t_morning %}
      late_night
    {% elif t >= t_evening %}
      evening
    {% elif t >= t_day %}
      day
    {% else %}
      morning
    {% endif %}

action:
  - choose:
      # 1. OVERRIDE MODE (Makeup)
      - conditions:
          - condition: template
            value_template: "{{ is_override }}"
        sequence:
          # Turn EVERYTHING on Bright Cool White
          - service: light.turn_on
            target: !input light_main
            data:
              kelvin: 5000
              brightness_pct: 100
              transition: !input transition_time
          - service: light.turn_on
            target:
              entity_id: !input light_night
            data:
              kelvin: 5000
              brightness_pct: 100
              transition: !input transition_time

      # 2. TURN OFF (No Motion & No Override)
      - conditions:
          - condition: trigger
            id: "motion_off"
          - condition: template
            value_template: "{{ not is_override }}"
        sequence:
          - service: light.turn_off
            target: !input light_main
            data:
              transition: !input transition_time
          - service: light.turn_off
            target:
              entity_id: !input light_night
            data:
              transition: !input transition_time

      # 3. TURN ON / UPDATE (Motion Active OR Schedule Change)
      - conditions:
          - condition: template
            value_template: "{{ is_motion }}"
          - condition: template
            value_template: "{{ not is_override }}"
        sequence:
          - choose:
              # PHASE: MORNING (Cool, Bright)
              - conditions:
                  - condition: template
                    value_template: "{{ current_phase == 'morning' }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_main
                    data:
                      kelvin: 4000
                      brightness_pct: !input bri_morning
                      transition: !input transition_time
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      kelvin: 4000
                      brightness_pct: !input bri_morning
                      transition: !input transition_time

              # PHASE: DAY (Neutral, Bright)
              - conditions:
                  - condition: template
                    value_template: "{{ current_phase == 'day' }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_main
                    data:
                      kelvin: 3500
                      brightness_pct: !input bri_day
                      transition: !input transition_time
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      kelvin: 3500
                      brightness_pct: !input bri_day
                      transition: !input transition_time

              # PHASE: EVENING (Warm, Dim)
              - conditions:
                  - condition: template
                    value_template: "{{ current_phase == 'evening' }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_main
                    data:
                      kelvin: 2200
                      brightness_pct: !input bri_evening
                      transition: !input transition_time
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      kelvin: 2200
                      brightness_pct: !input bri_evening
                      transition: !input transition_time

              # PHASE: LATE NIGHT (Red/Amber, Dark)
              - conditions:
                  - condition: template
                    value_template: "{{ current_phase == 'late_night' }}"
                sequence:
                  # Hue Go -> RED
                  - service: light.turn_on
                    target:
                      entity_id: !input light_night
                    data:
                      rgb_color: [255, 67, 0] # Deep Orange/Red
                      brightness_pct: !input bri_night
                      transition: !input transition_time
                  
                  # Main Lights -> OFF or DIM Warm
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ enable_main_night }}"
                        sequence:
                          - service: light.turn_on
                            target: !input light_main
                            data:
                              kelvin: 2200
                              brightness_pct: !input bri_main_night
                              transition: !input transition_time
                    default:
                      - service: light.turn_off
                        target: !input light_main
                        data:
                          transition: !input transition_time