blueprint:
  name: "Circadian Living Room Lights v1.2.0"
  description: >
    **Version: 1.2.0**
    
    A comprehensive lighting automation for the Living Room that adapts to human presence, 
    circadian rhythms, and specific family routines.
    
    **Features:**
    - **Fully Configurable Profiles:** Customize Time, Kelvin, and Brightness for Dinner, Toddler, Evening, and Night.
    - **Manual Override:** Pause automation via a Switch or Input Boolean (e.g., for Movie Night).
    - **Daylight Harvesting:** Auto-Off if naturally bright (>400 lux).
    - **Flicker Protection:** Hybrid Lux logic prevents rapid toggling.
    - **Presence Timeout:** Configurable delay before turning off lights.
    
  domain: automation
  input:
    light_entity:
      name: Lights
      description: Select one or multiple lights to control.
      selector:
        entity:
          domain: light
          multiple: true
    presence_entity:
      name: Presence Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    presence_timeout:
      name: Presence Timeout
      description: "Wait this long after motion clears before turning off lights (Default: 5 min)."
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: min
    illuminance_entity:
      name: Illuminance (Lux) Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    override_entity:
      name: Manual Override Switch
      description: "If ON, automation pauses. Use a Helper (Input Boolean) toggled by your Remote."
      default: []
      selector:
        entity:
          domain: 
            - input_boolean
            - switch
    
    # --- Thresholds ---
    lux_on_threshold:
      name: Turn On Threshold
      description: "Lights turn ON if Lux drops below this (Default: 150)."
      default: 150
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
    lux_off_threshold:
      name: Turn Off Threshold (Daylight Harvesting)
      description: "Lights turn OFF if Lux stays above this (Default: 400)."
      default: 400
      selector:
        number:
          min: 100
          max: 2000
          unit_of_measurement: lx
    lux_off_duration:
      name: Turn Off Duration
      description: "How long Lux must be high before turning off (Anti-Flicker)."
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min

    # --- DINNER PROFILE ---
    time_dinner:
      name: Dinner Start Time
      default: "18:00:00"
      selector:
        time:
    dinner_kelvin:
      name: Dinner Color (K)
      default: 3000
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: K
    dinner_bri:
      name: Dinner Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # --- TODDLER PROFILE ---
    time_toddler:
      name: Toddler Prep Start Time
      default: "19:00:00"
      selector:
        time:
    toddler_kelvin:
      name: Toddler Color (K)
      default: 2200
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: K
    toddler_bri:
      name: Toddler Brightness (%)
      default: 60
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # --- EVENING PROFILE ---
    time_evening:
      name: Evening Start Time
      default: "20:00:00"
      selector:
        time:
    evening_kelvin:
      name: Evening Color (K)
      default: 2700
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: K
    evening_bri:
      name: Evening Brightness (%)
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # --- NIGHT PROFILE ---
    time_night:
      name: Night Start Time
      default: "22:00:00"
      selector:
        time:
    night_kelvin:
      name: Night Color (K)
      default: 2200
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: K
    night_bri:
      name: Night Brightness (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # --- General Light Settings ---
    max_kelvin:
      name: Max Kelvin (Daylight)
      description: Used for Day Mode calculation.
      default: 4500
      selector:
        number:
          min: 2000
          max: 6500
          step: 100
          unit_of_measurement: K
    min_kelvin:
      name: Min Kelvin (Warm)
      description: Used for Day Mode calculation.
      default: 2200
      selector:
        number:
          min: 2000
          max: 4000
          step: 100
          unit_of_measurement: K

mode: restart
max_exceeded: silent

trigger:
  # 1. Presence Detected
  - platform: state
    entity_id: !input presence_entity
    to: "on"
    id: "presence_on"
  
  # 2. Presence Cleared (With Timeout)
  - platform: state
    entity_id: !input presence_entity
    to: "off"
    for: 
      minutes: !input presence_timeout
    id: "presence_off"
  
  # 3. Periodic Update (Circadian Shift)
  - platform: time_pattern
    minutes: "/5"
    id: "update_loop"

  # 4. Daylight Harvesting (Auto-OFF)
  - platform: numeric_state
    entity_id: !input illuminance_entity
    above: !input lux_off_threshold
    for: 
      minutes: !input lux_off_duration
    id: "lux_high"

  # 5. Daylight Fading (Auto-ON)
  - platform: numeric_state
    entity_id: !input illuminance_entity
    below: !input lux_on_threshold
    id: "lux_low"

  # 6. Override Turned OFF (Resume)
  - platform: state
    entity_id: !input override_entity
    to: "off"
    id: "override_resume"

variables:
  # Inputs
  target_lights: !input light_entity
  sensor_lux: !input illuminance_entity
  sensor_presence: !input presence_entity
  entity_override: !input override_entity
  threshold_on: !input lux_on_threshold
  val_max_k: !input max_kelvin
  val_min_k: !input min_kelvin
  
  # Time Slots
  t_dinner: !input time_dinner
  t_toddler: !input time_toddler
  t_evening: !input time_evening
  t_night: !input time_night
  
  # Profile Settings
  k_dinner: !input dinner_kelvin
  b_dinner: !input dinner_bri
  k_toddler: !input toddler_kelvin
  b_toddler: !input toddler_bri
  k_evening: !input evening_kelvin
  b_evening: !input evening_bri
  k_night: !input night_kelvin
  b_night: !input night_bri

action:
  # 1. Check Override First
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ entity_override != [] and is_state(entity_override, 'on') }}"
        sequence:
          - stop: "Manual Override is ON. Automation halted."

  # 2. Calculate Logic Variables
  - variables:
      current_lux: "{{ states(sensor_lux) | float(0) }}"
      is_presence_on: "{{ is_state(sensor_presence, 'on') }}"
      
      # Determine Current Mode based on Time
      mode: >
        {% set t_now = now().strftime('%H:%M:%S') %}
        {% if t_now >= t_night %} night
        {% elif t_now >= t_evening %} evening
        {% elif t_now >= t_toddler %} toddler
        {% elif t_now >= t_dinner %} dinner
        {% elif t_now >= '06:00:00' %} day
        {% else %} night {% endif %}
      
      # Calculate Target Settings
      target_kelvin: >
        {% if mode == 'dinner' %} {{ k_dinner }}
        {% elif mode == 'toddler' %} {{ k_toddler }}
        {% elif mode == 'evening' %} {{ k_evening }}
        {% elif mode == 'night' %} {{ k_night }}
        {% else %}
          {# Day Mode: Use Sun Elevation #}
          {% set elev = state_attr('sun.sun', 'elevation') | float(0) %}
          {% set pct = (elev + 6) / 51 %}
          {% set k = (val_max_k - val_min_k) * pct + val_min_k %}
          {# Clamp k between val_min_k and val_max_k #}
          {{ [val_min_k, [val_max_k, k] | min] | max | int }}
        {% endif %}
        
      target_brightness: >
        {% if mode == 'dinner' %} {{ b_dinner }}
        {% elif mode == 'toddler' %} {{ b_toddler }}
        {% elif mode == 'evening' %} {{ b_evening }}
        {% elif mode == 'night' %} {{ b_night %}
        {% else %} 100 {% endif %}

  - choose:
      # SCENARIO 1: TURN OFF (Presence Cleared OR High Lux)
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "presence_off"
              - condition: trigger
                id: "lux_high"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
            data:
              transition: 5

      # SCENARIO 2: TURN ON (Presence Detected OR Lux Low OR Override Resume)
      - conditions:
          - condition: template
            value_template: "{{ is_presence_on }}"
          - condition: or
            conditions:
              # Triggered by presence -> Check Lux
              - condition: and
                conditions:
                  - condition: trigger
                    id: "presence_on"
                  - condition: template
                    value_template: "{{ current_lux < threshold_on }}"
              # Triggered by Lux Low -> Check if we are already present
              - condition: trigger
                id: "lux_low"
              # Triggered by Override Resume -> Restore state immediately
              - condition: trigger
                id: "override_resume"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              kelvin: "{{ target_kelvin }}"
              brightness_pct: "{{ target_brightness }}"
              transition: 2

      # SCENARIO 3: UPDATE LOOP (Already On)
      - conditions:
          - condition: trigger
            id: "update_loop"
          # Only run if AT LEAST ONE of the target lights is ON
          - condition: template
            value_template: >
              {{ expand(target_lights) | selectattr('state', 'eq', 'on') | list | count > 0 }}
          # Safety: Don't update if lux is crazy high
          - condition: template
            value_template: "{{ current_lux < (threshold_on + 300) }}" 
        sequence:
          - service: light.turn_on
            target:
              # Only target the lights that are currently ON
              entity_id: >
                {{ expand(target_lights) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list }}
            data:
              kelvin: "{{ target_kelvin }}"
              brightness_pct: "{{ target_brightness }}"
              transition: 30