blueprint:
  name: "Dinner Table Lights v1.0.0 (Circadian & Battery)"
  description: >
    **Version: 1.0.0**
    
    A specialized automation for dining table lighting using portable Hue Go lights and mmWave presence detection.
    
    **Features:**
    *   **Mealtime Logic:** Lights only auto-activate during configured Breakfast, Lunch, and Dinner windows.
    *   **Circadian Warmth:** Uses warmer-than-standard tones (2200K-4000K) for a cozy dining atmosphere.
    *   **Presence Control:** Configurable timeout (default 5 min).
    
    *Note: Battery monitoring features have been removed due to hardware limitations (Hue Go does not expose battery level to HA).*
    
  domain: automation
  input:
    # --- Devices ---
    motion_sensor:
      name: Presence Sensor (mmWave)
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    light_entity:
      name: Dining Table Light(s) (Hue Go)
      selector:
        target:
          entity:
            domain: light

    # --- Manual Override ---
    override_entity:
      name: Override / Manual Mode
      description: When ON, lights stay ON (ignoring time/presence).
      default: []
      selector:
        entity:
          domain: input_boolean

    # --- Meal Times & Settings ---
    # Breakfast
    time_breakfast_start:
      name: Breakfast Start
      default: "07:00:00"
      selector:
        time:
    time_breakfast_end:
      name: Breakfast End
      default: "10:00:00"
      selector:
        time:
    bri_breakfast:
      name: Breakfast Brightness (3500K)
      default: 80
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}

    # Lunch
    time_lunch_start:
      name: Lunch Start
      default: "12:00:00"
      selector:
        time:
    time_lunch_end:
      name: Lunch End
      default: "14:00:00"
      selector:
        time:
    bri_lunch:
      name: Lunch Brightness (4000K)
      default: 100
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}

    # Dinner
    time_dinner_start:
      name: Dinner Start
      default: "17:30:00"
      selector:
        time:
    time_dinner_end:
      name: Dinner End
      default: "20:30:00"
      selector:
        time:
    bri_dinner:
      name: Dinner Brightness (2200K)
      default: 60
      selector:
        number: {min: 1, max: 100, unit_of_measurement: "%"}

    # --- General Settings ---
    motion_delay:
      name: Presence Timeout
      description: Turn off after no presence for this long.
      default: 5
      selector:
        number: {min: 1, max: 60, unit_of_measurement: "min"}
    transition_time:
      name: Transition Time
      default: 2
      selector:
        number: {min: 0, max: 10, unit_of_measurement: "s"}

mode: restart
max_exceeded: silent

trigger:
  # 1. Presence
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: "presence_active"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: 
      minutes: !input motion_delay
    id: "presence_clear"
  
  # 2. State
  - platform: state
    entity_id: !input override_entity
    id: "state_change"

  # 3. Schedule Checks (Update light if it's already on)
  - platform: time
    at: !input time_breakfast_start
    id: "schedule_change"
  - platform: time
    at: !input time_breakfast_end
    id: "schedule_change"
  - platform: time
    at: !input time_lunch_start
    id: "schedule_change"
  - platform: time
    at: !input time_lunch_end
    id: "schedule_change"
  - platform: time
    at: !input time_dinner_start
    id: "schedule_change"
  - platform: time
    at: !input time_dinner_end
    id: "schedule_change"

variables:
  # Inputs
  sensor_presence: !input motion_sensor
  entity_override: !input override_entity
  
  t_bk_start: !input time_breakfast_start
  t_bk_end: !input time_breakfast_end
  t_lu_start: !input time_lunch_start
  t_lu_end: !input time_lunch_end
  t_dn_start: !input time_dinner_start
  t_dn_end: !input time_dinner_end

  # State Calculations
  is_presence: "{{ is_state(sensor_presence, 'on') }}"
  
  is_override: >
    {% if entity_override %}
      {{ is_state(entity_override, 'on') }}
    {% else %}
      false
    {% endif %}

  # Time Window Logic
  current_time: "{{ now().strftime('%H:%M:%S') }}"
  
  is_breakfast: "{{ t_bk_start <= current_time < t_bk_end }}"
  is_lunch: "{{ t_lu_start <= current_time < t_lu_end }}"
  is_dinner: "{{ t_dn_start <= current_time < t_dn_end }}"
  
  is_meal_time: "{{ is_breakfast or is_lunch or is_dinner }}"

action:
  - choose:
      # 1. OVERRIDE MODE (Manual)
      - conditions:
          - condition: template
            value_template: "{{ is_override }}"
        sequence:
          # Just ensure it's ON. User controls brightness/color manually, 
          # OR we could force a default "Work" mode. 
          # Requirement said: "manual control... outside of time blocks".
          # Usually Overrides shouldn't fight the user. But let's ensure it's ON.
          - service: light.turn_on
            target: !input light_entity
            data:
              transition: !input transition_time
      
      # 2. TURN OFF (No Presence or Not Meal Time)
      # We turn off if: (Presence Cleared) OR (Presence Active BUT Not Meal Time)
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "presence_clear"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ not is_meal_time }}"
                  - condition: template
                    value_template: "{{ not is_override }}"
        sequence:
          - service: light.turn_off
            target: !input light_entity
            data:
              transition: !input transition_time

      # 3. NORMAL OPERATION (Presence & Meal Time)
      - conditions:
          - condition: template
            value_template: "{{ is_presence }}"
          - condition: template
            value_template: "{{ is_meal_time }}"
        sequence:
          - choose:
              # BREAKFAST (3500K)
              - conditions: "{{ is_breakfast }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_entity
                    data:
                      kelvin: 3500
                      brightness_pct: !input bri_breakfast
                      transition: !input transition_time
              
              # LUNCH (4000K)
              - conditions: "{{ is_lunch }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_entity
                    data:
                      kelvin: 4000
                      brightness_pct: !input bri_lunch
                      transition: !input transition_time

              # DINNER (2200K)
              - conditions: "{{ is_dinner }}"
                sequence:
                  - service: light.turn_on
                    target: !input light_entity
                    data:
                      kelvin: 2200
                      brightness_pct: !input bri_dinner
                      transition: !input transition_time