blueprint:
  name: "Toddler Sleep Trainer & Nightlight v1.1.1 (Debug)"
  description: >
    **Version: 1.1.1 (Debug Edition)**
    
    **DEBUGGING MODE:** This version includes a Persistent Notification action to confirm it is running.
    
    **IMPORTANT:** Restart Home Assistant after importing.
    
    An advanced nightlight automation designed for toddlers.
    
  domain: automation
  input:
    light_entity:
      name: Night Light
      selector:
        entity:
          domain: light
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          
    # --- Scheduling ---
    wakeup_time_mon:
      name: Monday Wakeup
      default: "07:00:00"
      selector:
        time:
    wakeup_time_tue:
      name: Tuesday Wakeup
      default: "07:00:00"
      selector:
        time:
    wakeup_time_wed:
      name: Wednesday Wakeup
      default: "07:00:00"
      selector:
        time:
    wakeup_time_thu:
      name: Thursday Wakeup
      default: "07:00:00"
      selector:
        time:
    wakeup_time_fri:
      name: Friday Wakeup
      default: "07:00:00"
      selector:
        time:
    wakeup_time_sat:
      name: Saturday Wakeup
      default: "07:30:00"
      selector:
        time:
    wakeup_time_sun:
      name: Sunday Wakeup
      default: "07:30:00"
      selector:
        time:

    # --- Colors & Brightness ---
    night_color:
      name: Night Color (Sleep)
      default: [255, 67, 0]
      selector:
        color_rgb:
    wakeup_color:
      name: Wakeup Color
      default: [0, 255, 0]
      selector:
        color_rgb:
    
    night_brightness:
      name: Night Brightness (Sleep)
      default: 5
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    boost_brightness:
      name: Night Brightness (Motion Boost)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    wakeup_brightness:
      name: Wakeup Brightness
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # --- Timing ---
    transition_time:
      name: Transition Time
      default: 2
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: "s"
    motion_clear_delay:
      name: Motion Clear Delay
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: "s"

mode: restart
max_exceeded: silent

trigger:
  # 1. Start of Routine
  - platform: time
    at: "18:00:00"
    id: "night_start"
  
  # 2. Motion triggers
  - platform: state
    entity_id: !input motion_entity
    to: "on"
    id: "motion_detected"
  - platform: state
    entity_id: !input motion_entity
    to: "off"
    for: !input motion_clear_delay
    id: "motion_cleared"

  # 3. Dynamic Wakeup Triggers
  - platform: time
    at: !input wakeup_time_mon
    id: "wakeup_schedule"
  - platform: time
    at: !input wakeup_time_tue
    id: "wakeup_schedule"
  - platform: time
    at: !input wakeup_time_wed
    id: "wakeup_schedule"
  - platform: time
    at: !input wakeup_time_thu
    id: "wakeup_schedule"
  - platform: time
    at: !input wakeup_time_fri
    id: "wakeup_schedule"
  - platform: time
    at: !input wakeup_time_sat
    id: "wakeup_schedule"
  - platform: time
    at: !input wakeup_time_sun
    id: "wakeup_schedule"

  # 4. Init
  - platform: homeassistant
    event: start
    id: "init"

variables:
  # Simple Input Mapping (Safe Global Variables)
  sensor_motion: !input motion_entity
  bri_night: !input night_brightness
  bri_boost: !input boost_brightness
  
  # Map Time Inputs to Variables
  t_mon: !input wakeup_time_mon
  t_tue: !input wakeup_time_tue
  t_wed: !input wakeup_time_wed
  t_thu: !input wakeup_time_thu
  t_fri: !input wakeup_time_fri
  t_sat: !input wakeup_time_sat
  t_sun: !input wakeup_time_sun

action:
  # 1. DEBUG NOTIFICATION (Confirm Run)
  - service: persistent_notification.create
    data:
      title: "NightLight Debug"
      message: "Automation Triggered! Checking Logic..."

  # 2. Calculate Logic Variables (Inside Action -> generates Trace on error)
  - variables:
      wakeup_time_today: >
        {{ [t_mon, t_tue, t_wed, t_thu, t_fri, t_sat, t_sun][now().weekday()] }}
      current_time: "{{ now() }}"
      today_wakeup_dt: "{{ today_at(wakeup_time_today) }}"
      today_end_dt: "{{ today_at(wakeup_time_today) + timedelta(hours=1) }}"
      is_wakeup_window: >
        {{ today_wakeup_dt <= current_time < today_end_dt }}
      is_night_window: >
        {{ current_time.hour >= 18 or current_time < today_wakeup_dt }}
      is_motion_active: "{{ is_state(sensor_motion, 'on') }}"

  # 3. Execute Logic
  - choose:
      # SCENARIO 1: WAKEUP
      - conditions:
          - condition: template
            value_template: "{{ is_wakeup_window }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              rgb_color: !input wakeup_color
              brightness_pct: !input wakeup_brightness
              transition: !input transition_time

      # SCENARIO 2: NIGHT (SLEEP)
      - conditions:
          - condition: template
            value_template: "{{ is_night_window }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              rgb_color: !input night_color
              brightness_pct: "{{ bri_boost if is_motion_active else bri_night }}"
              transition: !input transition_time

    # DEFAULT: OFF
    default:
      - service: light.turn_off
        target:
          entity_id: !input light_entity
        data:
          transition: !input transition_time

